model_type: transformer_lagr
data_path: /cfq2/sparql
data: cfq
weak_supervision: True
separate_encoders: False
share_encoder: True
batch_size: 512
lr: 0.0004
dropout: 0.1
epochs: 800
dim: 256
num_warmup_steps: 1000
transformer.encoder_n_layers: 4
transformer.decoder_n_layers: 4
transformer.n_heads: 8
n_graph_layers: 2
n_node_labels: 84
n_edge_labels: 5
eval_every: 20
